### ISSUE TITLE
No gulp

### ISSUE THREAD

**Issue by mtebong** [tushar-chauhan/generator-angular2-sass-gulp-heroku#1]
Love this generator!!! Exactly what i need but for the fact that when I run generator ("yo angular2-sass-gulp-heroku <project name>"), no gulpfile.js is generated. Neither does the package.json have any references to gulp. Is that expected?

**Comment by tushar-chauhan** [comment]
@mtebong sorry for a delayed response.
I was using gulp when I created this package to move assets to angular2 builds. I removed gulp from dependencies once angular-cli moved from System.js to Webpack.

Although, you can add and use gulp with this generator depending on your requirements.
I hope this clarifies your query, if so, then please close this issue.

**Comment by mtebong** [comment]
yeah. Gulp in essential for continuous builds and integration with gradle or maven. 
Thanks though.
